### ISSUE TITLE
fetch gpg key via https

### ISSUE THREAD

**Issue by maxinfernito** [xetus-oss/docker-ossec-server#4]
In https://github.com/xetus-oss/docker-ossec-server/blob/master/Dockerfile#L8 we're downloading gpg key via http, which pretty much destroys the concept of package signing. Sure, chance of getting MiTMed during deployment would be rather low, but given the wazuh website being available via https anyway, it's easy enough to fix. Could we switch to https?

**Comment by tkent** [comment]
Sure, that's a pretty easy change to make. I'll look into it shortly.

**Comment by tkent** [comment]
@thedawidbalut 

I've updated the master branch's Dockerfile to download the pgp key via https, so future builds will have a lower risk for MITM attacks.

I'm not going to create a new release though, since you can easily confirm the right PGP key is installed by checking in the image. No previous build suffered from a MITM attack, which isn't terribly surprising.

Thanks for the feedback!

**Comment by maxinfernito** [comment]
@tkent Absolutely agreed! Thanks for the change =)
